### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by DigitalSagittarius** [ghanu119/findinset_relation#3]
Return a empty array while using trait but query is run in phpmyadmin give result

**Comment by ghanu119** [comment]
Please add your code. 
How you have implemented?

Elaborate your issue.

**Comment by DigitalSagittarius** [comment]
![image](https://user-images.githubusercontent.com/73698250/123673592-4882f700-d85e-11eb-94a7-b21c0f080567.png)

**Comment by DigitalSagittarius** [comment]
sorry i cant to install throw composer so i download your source then i use it

**Comment by DigitalSagittarius** [comment]
i am using laravel 8

**Comment by DigitalSagittarius** [comment]
![image](https://user-images.githubusercontent.com/73698250/123673854-8e3fbf80-d85e-11eb-984f-42150c05a63e.png)

**Comment by DigitalSagittarius** [comment]
this my structure

**Comment by DigitalSagittarius** [comment]
![image](https://user-images.githubusercontent.com/73698250/123673996-bb8c6d80-d85e-11eb-8f2e-92a7471e1f37.png)
this my query log

**Comment by DigitalSagittarius** [comment]
![image](https://user-images.githubusercontent.com/73698250/123674162-ebd40c00-d85e-11eb-903b-d297cfed7e96.png)
i get locations as empty
but i run the query in phpmyadmin its give result

**Comment by DigitalSagittarius** [comment]
i have offer table with column location i save comma seperated value in location column the i get location like 
offers->location column[1,2,3]->location[1{},2{},3{}]

**Comment by ghanu119** [comment]
If you use `get()` method on model then check by calling  `first()` method on your offer model. It gives result or not.

**Comment by DigitalSagittarius** [comment]
can you explain well please

**Comment by DigitalSagittarius** [comment]
```
class Offer extends Model
{
    public function locations()
    {
        return $this->FindInSetMany( Location::class, 'location', 'id');
    }
}
```
this my model

**Comment by DigitalSagittarius** [comment]
```
class OfferController extends Controller
{
       public function Offers(Request $request)
	{
	    $offer	= Offer::select('id','location','image')->with(['locations'])->get();
	    return  ['offers'=>$offer];
       }
}
```
this my contoller

**Comment by DigitalSagittarius** [comment]
i get result but get like below
```
class OfferController extends Controller
{
       public function Offers(Request $request)
	{
	    $offer	= Offer::select('id','location','image')->with(['locations'])->get();
	    dd($offer[0]->location()->get());
       }
}
```

**Comment by DigitalSagittarius** [comment]
but i need its should append in main object right?

**Comment by ghanu119** [comment]
I have updated the new code. update the file `FindInSetRelation.php` code in your `FindInSetRelation.php`.

**Comment by ghanu119** [comment]
This package will not work on array collection. This will only work for a single record. In array collection, it will work only for the first record and the rest of the records won't be fetched the relation data.

**Comment by DigitalSagittarius** [comment]
any idea about get the item in array collection because i need a result like that

**Comment by DigitalSagittarius** [comment]
you are really amazing person i get quick response from you thanks a lot help me get it like that

**Comment by ghanu119** [comment]
Use `map` on your collection result:
`
$offer	= Offer::select('id','location','image')->get();
$offer->map( function ( $item ) {
     return $item->load('locations');
});
`

**Comment by DigitalSagittarius** [comment]
> This package will not work on array collection. This will only work for a single record. In array collection, it will work only for the first record and the rest of the records won't be fetched the relation data.

yeah now is take first one

**Comment by DigitalSagittarius** [comment]
> Use `map` on your collection result:
> `$offer = Offer::select('id','location','image')->get(); $offer->map( function ( $item ) { return $item->load('locations'); });`

thanks so much

**Comment by DigitalSagittarius** [comment]
its working.without using map function can we get result

**Comment by ghanu119** [comment]
No, right now you have to use the map function and need to load relation data for each data.

**Comment by DigitalSagittarius** [comment]
okay i am also try to get data without map function if you get any idea please publish thank you so much for you invaluable time

**Comment by DigitalSagittarius** [comment]
good night

**Comment by ghanu119** [comment]
Sure. 
Thanks for creating an issue with this package.
For using this package, thanks, too.

I am closing this issue now.
