### ISSUE TITLE
Cant use with Laravel 9

### ISSUE THREAD

**Issue by mrsnax** [ghanu119/findinset_relation#4]
Hi, 

I'm tried to include vendor with composer but I got errors

`Problem 1
    - Root composer.json requires ghanuz/relations dev-master -> satisfiable by ghanuz/relations[dev-master].
    - ghanuz/relations dev-master requires laravel/framework 5.3|5.4|5.6|5.7|5.8|^6.0.0|^7.0.0|8.* -> found laravel/framework[v5.3.0, ..., v5.8.0, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).`

Please update for Laravel 9

**Comment by ghanu119** [comment]
@mrsnax 
I have added Laravel 9 in composer, you can take pull and check.
Please note that I did not use the test case for Laravel 9.

**Comment by mrsnax** [comment]
> I have added Laravel 9 in composer, you can take pull and check.


Hi again

after running composer again still got errors 

```
Problem 1
    - Root composer.json requires ghanuz/relations dev-master -> satisfiable by ghanuz/relations[dev-master].
    - ghanuz/relations dev-master requires laravel/framework 5.3|5.4|5.6|5.7|5.8|^6.0.0|^7.0.0|8.* -> found laravel/framework[v5.3.0, ..., v5.8.0, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require ghanuz/relations:*" to figure out if any version is installable, or "composer require ghanuz/relations:^2.1" if you know which you need.
```

**Comment by ghanu119** [comment]
@mrsnax 
`composer require ghanuz/relations:master`
It has laravel version 9 support.

**Comment by mrsnax** [comment]
> @mrsnax `composer require ghanuz/relations:master` It has laravel version 9 support.

There is no branch  master on [packagist.org](url)

![image](https://user-images.githubusercontent.com/6369589/155058808-a7cc01c3-b657-4c10-a24a-120d3dfa9733.png)

Here is the detail https://packagist.org/packages/ghanuz/relations#dev-master

**Comment by mrsnax** [comment]
Update it's done after clicking Update Package on Packagist.org

Before updating

![image](https://user-images.githubusercontent.com/6369589/155059193-2a5271ce-1bc6-4d94-b1e3-2e9441e37db6.png)

after updating

![image](https://user-images.githubusercontent.com/6369589/155059239-13498eb0-da91-426e-8a98-974bcdc68710.png)

and result of composer

```
mrsnax@MRSNAX-iMac e-tahti % composer require ghanuz/relations
Using version dev-master for ghanuz/relations
./composer.json has been updated
Running composer update ghanuz/relations
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking ghanuz/relations (dev-master b2c3b29)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading ghanuz/relations (dev-master b2c3b29)
  - Installing ghanuz/relations (dev-master b2c3b29): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/sail
Discovered Package: laravel/sanctum
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-ignition
Discovered Package: spatie/laravel-permission
Package manifest generated successfully.
81 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php artisan vendor:publish --tag=laravel-assets --ansi --force
No publishable resources for tag [laravel-assets].
Publishing complete.
```

Thank you @ghanu119
