### ISSUE TITLE
Output to array and ordering by

### ISSUE THREAD

**Issue by mrsnax** [ghanu119/findinset_relation#5]
Hi,

Can you make output to an array instead collection? And how to order by large number first?

**Comment by ghanu119** [comment]
@mrsnax 
Which version of Laravel you are using?
And provide an example where you want array instead of collection, I can get idea what you actually need.

**Comment by mrsnax** [comment]
> 
Hi @ghanu119 
It's the latest version of Laravel

**Comment by ghanu119** [comment]
@mrsnax 
Can't able to convert collection to array?
And also not able to make order in descending?

If you have any example then it is better to get into this.

**Comment by mrsnax** [comment]
> 

example : 
I call the from Foreign Keys seperated comma like this  : 

`return $this->FindInSetOne(SPP::class, 'ref_spp_id', 'id')->orderBy('id', 'desc')->limit(1);`

then the output : 

```
Array
(
    [0] => stdClass Object
        (
            [id] => 8
            [c_nomor_spp] => 9988988989898989110
            [c_asal] => DASAR
            [c_tgl] => 2022-05-04
            [c_tgl_akhir] => 2022-05-10
            [c_masa_tahanan] => 7
            [c_pidana] => 312
            [c_pasal] => NYOLONG
            [c_ket] => EVERYDAY GOZALI
            [c_status] => 1
            [ref_spp] => 8
            [ref_tahanan] => 7
            [ref_satker] => 2
            [ref_mako] => 1
            [ref_penyidik] => 2
            [as_dasar] => 1
            [as_draft] => 0
            [as_archive] => 0
        )
)
```

it should output like this : 

```
(
    [id] => 8
    [c_nomor_spp] => 9988988989898989110
    [c_asal] => DASAR
    [c_tgl] => 2022-05-04
    [c_tgl_akhir] => 2022-05-10
    [c_masa_tahanan] => 7
    [c_pidana] => 312
    [c_pasal] => NYOLONG
    [c_ket] => EVERYDAY GOZALI
    [c_status] => 1
    [ref_spp] => 8
    [ref_tahanan] => 7
    [ref_satker] => 2
    [ref_mako] => 1
    [ref_penyidik] => 2
    [as_dasar] => 1
    [as_draft] => 0
    [as_archive] => 0
)
```

it's mean doesn't have `[ 0]` at the beginning of the array


From the output still not ordering by `DESC`, if the output has `DESC` ordering, the key of `as_dasar` will  be `0`


trying to use function `toArray() ` but got this result : 

`Call to undefined method GhanuZ\FindInSet\FindInSetOne::toArray()`

**Comment by ghanu119** [comment]
@mrsnax 
Added a new version v2.2 for this.
`composer require ghanuz/relations "v2.2.x-dev"`

Tested on latest Laravel version `^9.11` and `toArray()` is working.
`OrderBy` is also working.

**Comment by mrsnax** [comment]
Thank you for update I will tried

Have a nice day!

**Comment by mrsnax** [comment]
Sorry to reopen issues again

i got error with : 

`Call to undefined method GhanuZ\FindInSet\FindInSetOne::getDefaultFor()`

**Comment by ghanu119** [comment]
@mrsnax 
This method exists in all the latest versions. 
Check your Laravel version into `composer.json`.
OR
Also clear cache and check again.

This is not a possible error of an undefined method.

**Comment by ghanu119** [comment]
@mrsnax 
Updated on `v2.2` version and also in `master`.
Get latest code and test.
